### ISSUE TITLE
Invoking a constructor doesn't match an error rule

### ISSUE THREAD

**Issue by unserialize** [VKCOM/nocolor#2]
**Describe the bug**
When I write `$m = new Model`, this is not seen as a dependency regardless of the `@color` tag above the `Model` class.

**To Reproduce**
PHP code:
```php
/** @color controller */
class Controller {
  static function act() {
    $m = new Model;
  }
}

/** @color model */
class Model {
  function act() {}
}
```
palette.yaml:
```yaml
demo:
- controller model: restricted dependency
```

**Expected behavior**
An error.

**Actual behavior**
No error.

BTW, if I insert a call `$m->act()` after the constructor call, this error is shown

**Comment by i582** [comment]
It looks like the point is that there is no explicit constructor and therefore 
no link is created between function and constructor.
Apparently, it is worth adding a constructor in such cases if it is not found.
